### PR TITLE
Resolve outstanding SplashKit sklibc issues

### PR DESCRIPTION
**Pull request by alexcu**
This pull request adds:
- Extends parameter parsing to read information such as `const`, pointer and reference
- Support for `unsigned int` and `unsigned char`
- Ensure overloaded function names are unique using an internally generated name
- Support for global attributes in header documentation block
- Update attribute rules for getters and setters to have only one and two parameters, respectively
- Add support for `static` attributes
- Multidimensional array support
- Function pointer support

In addition, IO is improved so that you can parse directly from the SplashKit core directory and output will be automatically added to an `out` folder.

### CODE REVIEW

**Comment by alexcu** [comment]
**32dc64e adds (const) C++ reference support to C pointers.**

@macite Not sure if this is all what's needed for sklibc pointer/references.

E.g., for `const` references, if we had:

``` cpp
int add_ten(const int &pointer);
```

this would be converted to the following C code:

``` cpp
int __sklib__add_ten__int_ref(const int *pointer) {
    const int __skparam__pointer = __skadapter__to_int(*pointer);
    int __skreturn = add_ten(__skparam__pointer);
    return __skadapter__to_int(__skreturn);
}
```

Whereas if we had a pointer:

``` cpp
void add_ten(int *pointer);
```

then this would generate:

``` cpp
void __sklib__add_ten__int_ptr(int *pointer) {
    int *__skparam__pointer = pointer;
    add_ten(__skparam__pointer);
}
```

**Comment by macite** [comment]
Also need:

`*pointer = __skparam_pointer;`

after the call before the return.

**Comment by alexcu** [comment]
👍 knew I was missing something.

**Comment by alexcu** [comment]
I thought dereferencing and modifying `__skparam_pointer` modifies `pointer`? Hence no need to copy back. I can't dereference `pointer` and make it equal to `__skparam_pointer` as they are both `int*`:

```
error: assigning to 'int' from incompatible type 'int *'; dereference with *
    *pointer = __skparam__pointer;
```

Have I botched something in the definition of the sklib function?

**Comment by macite** [comment]
Sorry I was thinking this was for pass by reference... not const reference.

With const ref, just ignore the pointer and pass by value across the boundary.

**Comment by alexcu** [comment]
No worries. In fact I just realised I hadn't implemented this for pass by non-const reference. Let me patch this up and I'll push a fix.

**Pull request merged**
