### PR TITLE
generate c# documents

### PR DESCRIPTION
**Pull request by DarrenSunandar**
# Description

Generating c# documents from headerdoc.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

First of all, I locate where the csharp.rb file.

Then, I add method to generate the C# XML based documentation comments from the existing headerdoc.

I add def convert_headerdoc_to_xml(headerdoc) and modify the def docs_signatures_for(function).

Finally, I execute the C# translator by using this command provided in the translator guides.

## Testing Checklist

- [ ] Tested with sktest
- [ ] Tested with skunit_tests

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have requested a review from ... on the Pull Request

### CODE REVIEW

**Review by Liquidscroll — CHANGES_REQUESTED** [review]
Okay there's a number of issues with this.

Running this, I get the following output:
image

There's 2 issues here:
- The function passed into `docs_signatures_for` does _not_ have a field with a `comments` key. If we print out each key-value pair instead, we get the following output: 
image

- This code is attempting to write the XML comments to the output file `api.json` as a part of the `docs` translator. This is incorrect, as this is used to generate the documentation for each function on splashkit.io. 

Instead, what you need to do is extract the specific details from the functions and insert it above the relevant function _in SplashKit.cs_. Take for example the `animation_count()` function above, we need to turn those details into the following and place it above `animation_count()`:

```
/// <summary> 
/// Returns the number of `animation`s within an `animation_script`.
/// </summary> 
///
/// <param name="script">The `animation_script` to count the animations in.</param> 
///
/// <returns>Returns an `int` equal to the total number of animations in the script.</returns>
```

**Comment by DarrenSunandar** [comment]
I've fix the code, can you review it again.

**Review by Liquidscroll — CHANGES_REQUESTED** [review]
This still does not work. The problem is that the `docs_signatures_for` is used to _generate api.json_. So, what this is currently doing is inserting the XML comments into the signature for the function in `api.json`, for example:

image

This file is used to generate the API page on Splashkit.io, here: https://splashkit.io/api/, where we don't want or need XML comments.

I'm not sure if you can directly insert comments like you're doing. You might be able to do it through overriding translator.post_execute on the CSharp translator. This might be difficult as there'll be multiple versions of the same function in SplashKit.cs which will probably add a lot of overhead if you try to search through the ~20k lines.

Another way, probably the better way, would be to modify the templates for CSharp. Have a look at the following:
https://github.com/splashkit/splashkit-translator/tree/master/res/translators/csharp/SplashKit/classes
https://github.com/splashkit/splashkit-translator/blob/master/res/translators/csharp/SplashKit/methods.cs.erb

These use the ERB templating system, see more information here: https://github.com/ruby/erb

**Comment by DarrenSunandar** [comment]
I've updated the code. Please review it again.

**Pull request closed without merging**
